NORMALIZATION PROBLEM

In [7]:
import numpy as np

# Create a random 5x5 ndarray
X = np.random.rand(5, 5)  # values between 0 and 1

# Normalized: (X - mean) / std
Xnorm = (X - X.mean()) / X.std()

print("Original matrix X:\n", X)
print("\nNormalized matrix Xnorm:\n", Xnorm)


Original matrix X:
 [[0.49248207 0.55316437 0.08148372 0.76135162 0.39074255]
 [0.20675486 0.82488701 0.48832024 0.83720906 0.29748397]
 [0.3059165  0.06730729 0.62170494 0.86093559 0.57648721]
 [0.01571551 0.45651486 0.39295845 0.4833257  0.6239417 ]
 [0.16206995 0.58472078 0.90337693 0.53942382 0.7984222 ]]

Normalized matrix Xnorm:
 [[-0.00230365  0.23626101 -1.61809075  1.05472237 -0.40227948]
 [-1.12560339  1.3045036  -0.01866536  1.35294616 -0.76891359]
 [-0.73576217 -1.67382359  0.50571944  1.44622393  0.32795173]
 [-1.87665002 -0.1437041  -0.39356796 -0.03830076  0.51451298]
 [-1.30127636  0.36032095  1.6130766   0.18224179  1.20046061]]


DIVISIBLE BY 3 PROBLEM

In [6]:
import numpy as np

# Create a 10x10 ndarray of squares of first 100 positive integers
A = np.arange(1, 101) ** 2
A = A.reshape(10, 10)

# Extract elements divisible by 3
divby3 = A[A % 3 == 0]

# Save result (make sure variable names match!)
np.save("divby3.npy", divby3)

print("Matrix A:\n", A)
print("\nElements divisible by 3:\n", divby3)


Matrix A:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
